# Start from the official Shiny image
FROM jd21/methylr2:241016
LABEL authors="Jyotirmoy Das (jyotirmoy.das@liu.se)" \
    description="Exploratory Data Analysis from Clinical Data"

# Copy your Shiny app files into the container
RUN rm -rf /srv/shiny-server/

